### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by deependranimiwal** [ansrivas/GNG#1]
I am having this error while this running the script. 

Little research from google suggest change in NumPy Version responsible for this error. 
![errorgng](https://user-images.githubusercontent.com/25401357/30900455-b8beea94-a381-11e7-8fc6-185dd3a338da.JPG)
Please suggest some solution. 

  File "C:\Users\india\Documents\hotify\GNG-master\images2gif.py", line 352, in getSubRectangles
    im2 = im[y0:y1,x0:x1]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by ansrivas** [comment]
Hi @deependranimiwal , 
I have cleaned up the code a bit for better usage. You can checkout master.

Wrote it long back and didn't maintain it afterwards, hopefully it would be easier to use now.
